
name: Package into a JAR 

on: [push, pull_request]

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: "11"
    
    - name: Cache build dependencies
      uses: actions/cache@v2.1.6
      with:
        path: "~/.m2"
        key: "package-cache"
        
    - name: Clone
      uses: actions/checkout@v2.4.0
      
    - name: Package
      run: mvn package --batch-mode -DskipTests --file pom.xml
      
    - name: Uplod as artifact
      uses: actions/upload-artifact@v2
      with:
        name: maven-build-scanner
        path: /home/runner/work/maven-build-scanner/maven-build-scanner/target/maven-build-scanner-1.0.0-SNAPSHOT-jar-with-dependencies.jar
